language: node_js

node_js:
  - stable
  - v0.10
  - v0.12
  - v4
  - v5

sudo: false

cache:
  directories:
    - node_modules

env:
  global:
    - secure: lGT6/L/pT/ZUMGmkcNafVqr/yneiicgMAXbA24Iu05wOWLw8VNQm/1LLBNfFHP208jd4CJCott1Obxt5qxtqeJe9ax38EWR1sWK2pdPWSzSfHfXCja8Pe1YASkzApDsz9veqQQw98PoyqkkphZs8rINikKrDPV6AP3GfNZ9gkhu4Atorms7ScJ4QISbHFvWPSQtAeF9GjsdVG1VFdVAJ9uz2dCd1L/raoIwJaqFdK54mXevBSh9SR96PPeGUzK9MrSc5A6R/vJSKtQ0DDIjuv14xT3Tmu0/H4uS9bJYg96FpeZjwl3ih5o39+wLKM3Ex01RkZFOvZP9iO6ohgiwRvNMDmSKTtSyQuSyqeygW/Xht6OW9PmH88mK2kJrONa8m5T7xjHWNnaXi47xc7ZKc4T8ePmVvqjpEX+AvrnnGLsj8b6MdkJGxvm+oz3jKwoas8dY9OPgAES2FVZyiWcR8TOYVM3IF+BbrU0EJL7WauXWWRAaBC0P9lTzKvJRDLPJxhtjAXyoh/9mApgPalKgYU6aKTFX0RTBaUKrD6pg0kkixhAP3rYfFgpNWcpqS0gfPP7E4d6eKXMCbzBFxIsXBbWh/n3cAW+nsZDejT5BwPEz0MiJnh0dqnMvkVKOVUYM2GnhffBhbipk4lS7oGYpj091aXBd2n7mr4dGP0O+av9U=

script:
  - npm test
  - npm run sa

after_script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly spec.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
  - rm -rf ./coverage
